version: '3'

networks: 
  wordpress:
    external: true
  proxy:
    external: true

services:

  main:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
    deploy:
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=${WORDPRESS_DOMAIN:-localhost}
        - com.df.port=80
    networks:
      - wordpress
      - proxy

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-wordpress}
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wordpress}
    networks:
      - wordpress